export const ADD_CHAT_MESSAGE_TO_STORE = 'ADD_CHAT_MESSAGE_TO_STORE';
export const CHANGE_CONTENT_FIELD_IN_STORE = 'CHANGE_CONTENT_FIELD_IN_STORE';
export const INCREMENT_COUNT_SHIPS_MYFIELD_IN_STORE = 'INCREMENT_COUNT_SHIPS_MYFIELD_IN_STORE';
export const DECREMENT_COUNT_SHIPS_MYFIELD_IN_STORE = 'DECREMENT_COUNT_SHIPS_MYFIELD_IN_STORE';
export const ADD_INFO_TO_STORE = 'ADD_INFO_TO_STORE';
export const CHANGE_GAME_PHASE_IN_STORE = 'CHANGE_GAME_PHASE_IN_STORE';
export const CHANGE_TURN_IN_STORE = 'CHANGE_TURN_IN_STORE';
export const INCREMENT_NUMBER_MOVES = 'INCREMENT_NUMBER_MOVES';